apiVersion: helm.crossplane.io/v1alpha1
kind: Release
metadata:
  name: wordpress-example
spec:
  forProvider:
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.19
    namespace: wordpress
    values: |
      param1: value1
      param2: 1
    set:
      - name: param1
        value: value2
    valuesFrom:
      - configMapKeyRef:
          key: values.yaml
          name: default-vals
          namespace: wordpress
          optional: false
      - secretKeyRef:
          key: svalues.yaml
          name: svals
          namespace: wordpress
          optional: false
  providerRef:
    name: local-provider
  reclaimPolicy: Delete
