apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: local-provider
spec:
  credentialsSecretRef:
    # Get secret name from service account
    name: <helm-provider-token-secret-name>
    namespace: crossplane-system
