apiVersion: apiextensions.crossplane.io/v1alpha1
kind: CompositeResourceDefinition
metadata:
  name: wordpressclusters.example.crossplane.io
spec:
  defaultComposition:
   name: wordpressclusters.example.crossplane.io
  connectionSecretKeys:
    - kubeconfig
  crdSpecTemplate:
    group: example.crossplane.io
    version: v1alpha1
    names:
      kind: WordpressCluster
      listKind: WordpressClusterList
      plural: wordpressclusters
      singular: wordpresscluster
    validation:
      openAPIV3Schema:
        description: A WordpressCluster is a composite resource that represents a K8S Cluster with Wordpress Installed
        type: object
        properties:
          spec:
            type: object
            properties:
              clusterVersion:
                type: string
                description: GKE cluster version
            required:
              - clusterVersion