apiVersion: helm.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: local-provider-config
spec:
  credentials:
  source: Secret
    secretRef:
      # Get secret name from service account
      name: <helm-provider-token-secret-name>
      namespace: crossplane-system
      # We rely on multiple keys in ProviderConfig secret, so, ignoring "spec.credentialsSecretRef.key"
      key: ignore
