apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: cluster-credentials
      namespace: crossplane-system
      key: kubeconfig
# identity:
#   type: GoogleApplicationCredentials
#   source: Secret
#   secretRef:
#     name: gcp-credentials
#     namespace: crossplane-system
#     key: credentials.json
