name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v0.1.0)'
        required: true

env:
  UPBOUND_BOT_USR: ${{ secrets.UPBOUND_BOT_USR }}
  UPBOUND_BOT_PSW: ${{ secrets.UPBOUND_BOT_PSW }}

jobs:
  create-tag:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Configure Git User
        run:  |
          git config --global credential.helper cache
          git config remote.origin.url https://${UPBOUND_BOT_USR}:${UPBOUND_BOT_PSW}@$(git config --get remote.origin.url | sed -e 's/https:\/\///')
          git config user.name "upbound-bot"
          git config user.email "info@crossplane.io"

      - name: Create Tag
        run: make -j2 tag
        env:
          VERSION: ${{ github.event.inputs.version }}
        